services:
  web:
    build: .
    ports:
      # http server
      - "8000:8000"
        # web socket server that remix uses for development
      - "8002:8002"
        # prisma studio, which can be run with `docker exec` when needed
      - "5555:5555"
    entrypoint:
      - yarn
      - dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    links:
      - db
    environment:
      DATABASE_URL: postgresql://app:app@db/app
      CONTACT_INQUIRY_PASSWORD: pass
    # Prisma is broken on arm; see https://github.com/prisma/prisma/issues/10761
    platform: linux/amd64
  db:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

volumes:
  node_modules:
  pg_data:
