services:
  web:
    image: ${IMAGE}
    build: .
    ports:
      # http server
      - "8000:8000"
    links:
      - db
    environment:
      DATABASE_URL: postgresql://app:app@db/app
      ADMIN_PASSWORD: pass
      SECRET_KEY: anything
  db:
    image: postgres:14
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

volumes:
  pg_data:
