name: CI/CD

on:
  push:
  pull_request:

jobs:

  ci:
    name: continuous integration checks
    runs-on: ubuntu-latest
    environment: Kubernetes
    steps:
      - uses: actions/checkout@v2
      - name: make check
        run: make check

  cd:
    name: continuous delivery
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: ci
    environment: Kubernetes
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: make setup
        env:
          # credentials are used for terraform state bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make setup

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: jdevries3133
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: setup kubectl
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: push container to Docker Hub
        run: make push

      - name: deploy to Kubernetes with terraform
        env:
          # credentials are used for terraform state bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make deploy
